src/landmask.jl

fix: binarize_landmask

---

src/tracker/matchcorr.jl
src/tracker/tracker.jl
test/test-matchcorr.jl

fix: timedeltas as floats

---

src/segmentation_a_direct.jl

fix: suppress kmeans output

---

src/segmentation_a_direct.jl

fix: println => @info

---

src/tracker/tracker-funcs.jl

Handle collisions bottom-up in case of collision multiplicity. #308

fix: resolvecollisions!

---

src/tracker/tracker-funcs.jl

docs: update MatchedPairs

---

src/regionprops.jl

Came across this while prototyping things with HDF5. #312

fix: update regionprops_table docstring example

---

src/regionprops.jl
test/test-regionprops.jl

feat: add orientation to default props

---

notebooks/track-floes/track-floes.ipynb

To address changes in format of input params to  the `pairfloes` function.

update: track notebook

---

Project.toml

feat: v0.3.0 with floe labeling

---

Project.toml
src/tracker/tracker.jl

docs: update pairfloes docstring

---

.github/workflows/trigger-docker-julia.yml

fix: format of input for token

---

.github/workflows/trigger-docker-julia.yml

New test now that a `workflow_dispatch` param has been added to the triggered workflow at ice-floe-tracker-pipeline.

test: update wait time

---

.github/workflows/CompatHelper.yml

378 add compathelper

---

.github/workflows/CI.yml

- checks for both ubuntu (x64) and macos (arm64)
- Julia versions  ['1.9', '1.10', '~1.11.0-0']

ci: update matrix to include multiple Julia versions

---

src/histogram_equalization.jl
test/test-conditional-adaptive-histeq.jl

Refactoring intended to facilitate integration into pipeline workflow.

437 integrate conditional adaptive hist eq

---

.github/workflows/CheckNotebooks.yml
notebooks/track-floes/track-floes.ipynb

fix: update notebooks

---

Project.toml
README.md

Updating to version 0.6.0 after new landmasking fixes and project build fixes.

update source pkg version

---

src/histogram_equalization.jl
test/test-conditional-adaptive-histeq.jl

For wateshed workflow.
Closes #475

feat: histeq

---

docs/src/index.md

Added some sections to the index.md file and a list of contributors and references.

Adding to the landing page for the docs

---

Project.toml
src/tracker/tracker-funcs.jl

The previous PR #532 was in error – ended up causing a problem with method overwriting.

fix: method overwriting error

---

src/IceFloeTracker.jl
src/regionprops.jl
src/tracker/tracker-funcs.jl

The most important changes include adding new export functions and changes in documentation.
* [`src/IceFloeTracker.jl`](diffhunk://#diff-85d7f442c7361ae077cc64904ad09c8f64bb72be39f86559698038ba40db79f6R55-R57): Added new export functions `addfloemasks!`, `add_passtimes!`, `addψs!`, and `long_tracker` to the list of exports for the tracker.

feat: export tracker functions

---

src/validation_data.jl
test/segmentation_utils.jl
test/test-segmentation-lopez-acosta-2019.jl

Simplify test code for LopezAcosta2019

test[LopezAcosta2019]: deduplicate test code

---

src/preprocess_tiling.jl

Add an argument to process intermediate results in the LopezAcosta2019Tiling functor, 
- Analog of #675.

feat[LopezAcosta2019Tiling]: add intermediate results callback

---

test/test-preprocess-tiling.jl

Save intermediate results from LopezAcostaTiling2019 to file in testing
- Includes changes from #675

test[LopezAcostaTiling2019]: save intermediate results

---

src/gradient_functions.jl
src/nonlinear_diffusion.jl
test/test-gradient-functions.jl

This pull request introduces a new modular system for handling gradient functions used in nonlinear diffusion algorithms, particularly for the Perona-Malik diffusion method. It refactors the code to allow easy addition of new gradient functions, improves error handling and validation, and adds comprehensive tests for the new functionality. The main changes are grouped below:
**Gradient Function Abstraction and Refactoring:**
* Introduced a new module `gradient_functions.jl` that defines the supported gradient functions (`exponential` and `inverse_quadratic`) and a `SupportedFunctions` struct to manage them. This abstraction allows for easy extension and consistent access to available functions.
* Refactored `PeronaMalikDiffusion` to validate the gradient function name using the new …

Consolidate gradient functions
