WilhelmusLab/IceFloeTracker.jl

src/IceFloeTracker.jl
test/runtests.jl

Re-exporting HDF5, PyCall, Dates, DataFrames for IFTPipeline.

feat: dep exports for IFTPipeline

---

Project.toml
src/IceFloeTracker.jl
test/test-misc.jl

This approach is working well with IFTPipeline!

feat: hardcode pkg version number

---

README.md

Just some cleanup and adding a reference to the IFTPipeline in this README.

docs: remove old readme content and reference new pipeline repo

---

src/IceFloeTracker.jl
test/test-misc.jl

This PR updated the exported IFTVERSION variable to current. It was two versions behind.

update exported ift version number for the cli build

---

Project.toml
README.md

- Add versioning instructions to readme
- Update version to v0.4.2

update: add versioning instructions

---

Project.toml
src/IceFloeTracker.jl
test/test-misc.jl

Two more places needed updating.

chore: update version nums

---

.github/workflows/CI.yml
.github/workflows/documentation.yml
src/IceFloeTracker.jl
src/normalization.jl

Update sample function call to include `landmask_no_dilate`.

Fix imsharpen docstring

---

src/normalization.jl

Extract logic for unsharp mask to specialized function leveraging built in `clamp`.

feat: unsharp mask

---

src/IceFloeTracker.jl

Remove use of `eval` in the `__init__` function as it might be breaking interactions with IFTPipeline.jl.

refactor: streamline package imports and initialization

---

src/tracker/tracker-funcs.jl

... rather than shadowing it, which breaks the find_reflectance_peaks function in find_ice_labels.jl under some circumstances

fix: make sort! declaration extend Base.sort!

---

test/test-long-tracker.jl

This pull request includes a small change to the `test/test-long-tracker.jl` file. The change sets a random seed for reproducibility in the tests.
* [`test/test-long-tracker.jl`](diffhunk://#diff-9a101e482af868fa2ddf398664d27679cb0a7951d087435ac0832c3afcf0099bR2): Added `Random.seed!(123)` to ensure consistent results in tests.

test: set random seed for consistent results

---

src/tracker/long_tracker.jl
src/tracker/tracker-funcs.jl
src/tracker/tracker.jl

Add function required for manipulating the props DataFrame to include a UUID column. 
This is required for the long-tracker CLI. In the "old" tracker `IceFloeTracker.pairfloes`, this step was included, but in the "long" tracker `IceFloeTraker.long_tracker`, it isn't, so it needs to be made available to go into the `long_tracker` version of the CLI wrapper script.

Feat(long tracker): add separate UUID function

---

.github/workflows/CI.yml
requirements.txt
src/latlon.py

This pull request includes updates to the CI workflow and a fix for compatibility with a new version of the `rasterio` library. The most important changes involve updating the Python version and adjusting the code to work with the new library version.
CI workflow updates:
* [`.github/workflows/CI.yml`](diffhunk://#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8L30-R40): Updated the Python version from 3.11 to 3.12, added steps to install `setuptools` and `uv` for dependency conflict resolution, and modified the requirements installation process to use a compiled requirements file specific to Python 3.12.
Library compatibility fix:
* [`src/latlon.py`](diffhunk://#diff-d099fccab16463b94646549b3e7a193e5b067ec92992e2029250331ac5835bd3L17-R18): Modified the `getlatlon` …

Update workflow to Python 3.12

---

src/IceFloeTracker.jl

[Trying to have Julia build to pass]
This pull request includes updates to several package dependencies in the `src/IceFloeTracker.jl` file. The most important changes involve downgrading and upgrading specific versions of the packages used in the project.
Dependency updates:
* [`src/IceFloeTracker.jl`](diffhunk://#diff-85d7f442c7361ae077cc64904ad09c8f64bb72be39f86559698038ba40db79f6L96-R103): Downgraded `scikit-image` from version 0.24.0 to 0.20.0.
* [`src/IceFloeTracker.jl`](diffhunk://#diff-85d7f442c7361ae077cc64904ad09c8f64bb72be39f86559698038ba40db79f6L96-R103): Upgraded `rasterio` from version 1.3.7 to 1.4.3.
* [`src/IceFloeTracker.jl`](diffhunk://#diff-85d7f442c7361ae077cc64904ad09c8f64bb72be39f86559698038ba40db79f6L96-R103): Downgraded `jinja2` from version 3.1.2 to 3.1.0.
* …

chore: update versions for conda build

---

src/tracker/long_tracker.jl
src/tracker/tracker-funcs.jl
test/test-long-tracker.jl

Changes include the addition of a new function to drop short trajectories, modifications to existing functions [`long_tracker`], and updates to test cases.
Enhancements to trajectory output:
* [`src/tracker/tracker-funcs.jl`](diffhunk://#diff-7dbdc578b384fa8d2b5ae59a084e139d3d64f26659dd0251f12cfaa6fd2cf9c6R775-R790): Added a new function `drop_trajectories_length1` to filter out trajectories with only one floe. This function includes documentation and resets the ID of the remaining trajectories.
* [`src/tracker/long_tracker.jl`](diffhunk://#diff-c2a44906d1ee409a282e1c737d8d655be8ab0417c103a891e7eda6235ece547aR64): Integrated the new `drop_trajectories_length1` function into the `long_tracker` function to ensure short trajectories are removed before further processing.
Improvements to test …

567 throw out trajectories of length 1

---

docs/Manifest.toml
docs/Project.toml
docs/make.jl
docs/src/preprocessing.md

This pull request includes updates to the documentation and configuration for the IceFloeTracker project. The most important changes include updating the Documenter version, modifying the `make.jl` for compatibility with the new version, and improving the preprocessing documentation.
* [`docs/src/preprocessing.md`](diffhunk://#diff-45cbcc019c08ceeb37dc7a7f32bf603698a8c9793ae7385e10137e72e1a9383eR2-R25): Improved the preprocessing documentation by adding spaces, specifying the language for code blocks, and **_updating the image reference_**.
* [`docs/Project.toml`](diffhunk://#diff-6e0adb5e01dce01db395f52201532ad8fec022922489f34827886053953ce93fL5-R5): Updated the `Documenter` dependency version from "0.27" to "1.8.1".
* [`docs/make.jl`](diffhunk://#diff-4aae2d1c783cade58bd2cb13748da956e568 …

574 image not rendering in documentation

---

src/tracker/long_tracker.jl

This pull request includes a small change to the `src/tracker/long_tracker.jl` file. The change removes a line of code that accessed specific columns of the `trajectories` DataFrame, which appears to be redundant or unnecessary.
* [`src/tracker/long_tracker.jl`](diffhunk://#diff-c2a44906d1ee409a282e1c737d8d655be8ab0417c103a891e7eda6235ece547aL56): Removed the line accessing `:uuid`, `:passtime`, `:area_mismatch`, and `:corr` columns from the `trajectories` DataFrame.

chore: remove unnecessary line

---

notebooks/preprocessing-workflow/preprocessing-workflow.ipynb
notebooks/preprocessing-workflow/tiling.ipynb
notebooks/track-floes/track-floes.ipynb
test/config.jl
test/test-conditional-adaptive-histeq.jl
test/test-get-ice-masks.jl
test/test-preprocess-tiling.jl

The test filenames with "NE_Greenland" were incorrectly named -- the images show the Beaufort and Chukchi Seas, Greenland is not visible in the images. Furthermore, "reflectance" was used instead of "falsecolor" -- both truecolor and falsecolor images are corrected reflectance, so it doesn't make sense to use the word "reflectance" here.
I've not changed the filenames in example notebooks, I'll handle that in a separate pull request as I'm updating the notebooks today.

Changed filenames for accuracy

---

Project.toml
src/tracker/tracker-funcs.jl
src/tracker/tracker.jl

Re-introduce missing `getcentroid` signature which causes IFTPipeline.jl to fail.

fix: replace missing `getcentroid` signature

---

src/cloudmask.jl
src/histogram_equalization.jl
src/preprocess_tiling.jl
test/test-preprocess-tiling.jl

This pull request introduces enhancements to the cloud masking workflow, including adjustments to function parameters, improved mask creation logic, and updates to related workflows for better modularity and testing. The key changes are grouped below:
* Refactored cloud and ice mask creation logic in `_get_masks` to use element-wise comparisons with adjusted thresholds, improving clarity and accuracy. (`src/cloudmask.jl`, [src/cloudmask.jlL42-L48](diffhunk://#diff-82066102273585bdbf37d6f04d4f6d7afef5207d8f40fcf86daa762d2c5c609cL42-L48))
* Added `r_offset` parameter to `_get_masks`, `create_cloudmask`, and related functions to provide flexibility in threshold adjustments for cloud and ice separation. (`src/cloudmask.jl`, [[1]](diffhunk://#diff-82066102273585bdbf37d6f04d4f6d7afef5207d8f40fcf …

626 refactor elementwise division to avoid divide by 0 values

---

src/IceFloeTracker.jl
src/segmentation-lopez-acosta-2019.jl
src/utils.jl
src/validation_data.jl
test/segmentation_utils.jl
test/test-segmentation-lopez-acosta-2019.jl

LopezAcosta2019 now accepts a function which will be called with all the intermediate results.
This can be used to store the results to file, or pass the results out to the caller, or anything else the user requires. It makes the return signature of the LopezAcosta2019 functor consistent – it always only returns the segmented image.
Includes an additional factory function, `callable_store`, which creates a data store dictionary and a callback function to write data to the dictionary, as an example of a utility which could export the intermediate data.

feat[LopezAcosta2019]: add intermediate results callback

---

src/find_ice_labels.jl
test/test-find-ice-labels.jl

If no reflectance peaks, or if there are no valid pixels, return `Inf` rather than crashing for the peak value. This guarantees that nothing will be evaluated as larger than the result.

fix[find_reflectance_peaks]: if no reflectance peaks are found, return an Inf value

---

.github/workflows/CI.yml

Use the new secret CODECOV_TOKEN in the repository to show code coverage reports.

add CODECOV_TOKEN to CI

---

src/fill_holes.jl
src/validation_data.jl

Trying this again since I made a mess of my local github branch. This pull request only changes the spelling of "MAISIE" to the correct spelling "MASIE", and changes "grascale" to "grayscale" in one function doc.

Correcting typos
